# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(904, 637)
        self.label = QtWidgets.QLabel(parent=Menu)
        self.label.setGeometry(QtCore.QRect(380, 30, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=Menu)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(370, 450, 151, 81))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_cikis = QtWidgets.QPushButton(parent=self.horizontalLayoutWidget)
        self.btn_cikis.setObjectName("btn_cikis")
        self.horizontalLayout.addWidget(self.btn_cikis)
        self.layoutWidget = QtWidgets.QWidget(parent=Menu)
        self.layoutWidget.setGeometry(QtCore.QRect(200, 120, 500, 321))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_faturaolustur = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_faturaolustur.setMinimumSize(QtCore.QSize(0, 100))
        self.btn_faturaolustur.setObjectName("btn_faturaolustur")
        self.verticalLayout.addWidget(self.btn_faturaolustur)
        self.btn_faturagoruntule = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_faturagoruntule.setMinimumSize(QtCore.QSize(500, 100))
        self.btn_faturagoruntule.setObjectName("btn_faturagoruntule")
        self.verticalLayout.addWidget(self.btn_faturagoruntule)

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.label.setText(_translate("Menu", "MENÜ EKRANI"))
        self.btn_cikis.setText(_translate("Menu", "Çıkış"))
        self.btn_faturaolustur.setText(_translate("Menu", "E-FATURA OLUŞTUR"))
        self.btn_faturagoruntule.setText(_translate("Menu", "FATURALARI GÖRÜNTÜLE"))
